title: Jeremy Chang
description: 
show_downloads: true
google_analytics:

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

repository: jermy-c/resume
  
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-titles-from-headings